spring.application.name=equipe1-backend-sprin

spring.datasource.url=jdbc:postgresql://localhost:5432/student_projects_db
spring.datasource.username=postgres
spring.datasource.password=2209

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
